# Generated by Django 4.0.5 on 2023-09-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='gallerty_type',
            field=models.TextField(default='default', max_length=20),
        ),
    ]
